### ISSUE TITLE
Consistency in plotting functions

### ISSUE THREAD

**Issue by callumrollo** [callumrollo/glidertest#25]
We're adding a lot of plotting functionality to this library. For the end user, we want maximum utility and usability. To this end, we should consider a few points:

- [x] Order of arguments. Sometimes it's (ds, ax, var='default_var') sometimes (ax1, ax2, ds). Be consistent #26 
- [x] Return the figure and axes. This is nice for the user to then be able to e.g. finetune the xlims, add a title, gridlines etc. It's much simpler than taking all those things as kwargs. Just end the function with `return fig, ax` #26 
- [x] Create axes or take axes? It is nice to make a figure when a user doesn't pass one, and also have the flexibiity for the user to pass their own figure/axes to the function and have the function make a plot on it. See e.g. https://github.com/ioos/gliderpy/blob/def8d7d9d3435461fcb8cd6407cd87a1bf8cb4aa/gliderpy/plotting.py#L47 #27

**Comment by callumrollo** [comment]
@MOchiara we can work on this one together. I'll put in an example PR next week showing what I mean refactoring one of  the plotting functions. The goal of this is to make the plots functions as flexible and intuitive as possible, so that others can use this library without needing to understand the internal workings

**Comment by MOchiara** [comment]
Nice! Thanks for the suggestions =) I will do it after lunch

**Comment by MOchiara** [comment]
Sounds good! I can modify the functions so have the same order of variables and all and we can do the rest next week

**Comment by MOchiara** [comment]
Have we addressed all the points in the issue?

**Comment by callumrollo** [comment]
lgtm! Resolved in #26 and #27
